name: Update README

on:
  push:
    paths:
      - 'axer/template/**'
  release:
    types: [published, prereleased]
  workflow_dispatch:

jobs:
  update_readme:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # fetch all history and tags

      - name: Get latest Git tag
        id: get_tag
        run: |
          latest_tag=$(git describe --tags --abbrev=0 || echo "0.0.0")
          echo "tag=$latest_tag" >> $GITHUB_OUTPUT

      - name: Pull latest changes
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git pull origin main --rebase || true

      - name: Replace version in template README
        run: |
          sed "s/{{AXER_VERSION}}/${{ steps.get_tag.outputs.tag }}/" axer/template/template_README.MD > README.md

      - name: Commit and push updated README.md if changed
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add README.md
          if ! git diff --cached --quiet; then
            git commit -m "update version in README.md to ${{ steps.get_tag.outputs.tag }}"
            git push origin HEAD:main
          else
            echo "No changes to commit"
          fi
