name: Update README

on:
  push:
    tags:
      - '*'  # Trigger on tag push
    paths:
      - 'axer/template_README.MD'
  workflow_dispatch:

jobs:
  update_readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true
          ref: ${{ github.ref }}

      - name: Get latest Git tag
        id: get_tag
        run: |
          latest_tag=$(git describe --tags --abbrev=0 || echo "0.0.0")
          echo "tag=$latest_tag" >> $GITHUB_OUTPUT

      - name: Replace version in template_README.MD
        run: |
          sed "s/{{AXER_VERSION}}/${{ steps.get_tag.outputs.tag }}/" axer/template_README.MD > README.md

      - name: Determine branch or default to main
        id: extract_branch
        run: |
          ref=${{ github.ref }}
          if [[ "$ref" == refs/heads/* ]]; then
            echo "branch=${ref#refs/heads/}" >> $GITHUB_OUTPUT
          else
            echo "branch=main" >> $GITHUB_OUTPUT
          fi

      - name: Commit and push updated README.md
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add README.md
          git diff --cached --quiet || git commit -m "update version in README.md to ${{ steps.get_tag.outputs.tag }}"
          git push origin HEAD:${{ steps.extract_branch.outputs.branch }}
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
